import './style.css'
import './styles/tablet-style.css'
import './styles/mobile-style.css'
import './scripts/round-list.js'
import './scripts/crypto-ws.js'
import './word-by-word-anim.js'
import './scripts/pop-ups.js'
import './scripts/tablet-menu.js'